name: dc-gym
channels:
- pytorch
dependencies:
- python=3.8.5
- anaconda
- cudatoolkit=10.
- numpy
- pip
- pip:
  - gym==0.21.0
  - mujoco-py==2.1.2.14
  - numpy==1.23.5
  - torch==2.0.0
  - transformers==4.6.0
  - wandb==0.15.11
